# 用户模糊查询
POST http://localhost:9010/demo/employee/query
Content-Type: application/json

{
  "pageNum" : 1,
  "pageSize" : 15,
  "name" : "静"
}

###
# 抛异常的情况
POST http://localhost:9010/demo/employee/error
Content-Type: application/json

{
"pageNum" : 1,
"pageSize" : 15,
"name" : "静"
}

###
# 获取电话号码 - 测试流程日志 D:\yfst_logs\app-dem\trace.log
GET http://localhost:9010/demo/employee/phone?id=105

### 获取当前用户信息
GET http://localhost:9010/demo/employee/current/userInfo
Content-Type: application/json
userInfo: eyJ1c2VyVHlwZSI6MSwiYmFzZUluZm8iOnsidXNlcklkIjoxLCJ1c2VyTmFtZSI6IueuoeeQhuWRmCIsInJvbGVDb2RlIjoidGVzdC1yb2xlIiwicm9sZU5hbWUiOiLmtYvor5Xop5LoibIifX0=