server:
  port: 9010
  servlet:
    context-path: /demo

## 内部网关地址（本地环境）
com:
  yfst:
    feign:
      gateway:
        uri: https://cimptst.micxapp.com/lan/api


## 内部网关地址（测试机环境）
#com:
#  yfst:
#    feign:
#      gateway:
#        uri: http://app-base-gateway